name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Release
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Release

# jobs:
  # build_and_deploy_job:
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   runs-on: ubuntu-latest
  #   name: Build and Deploy Job
  #   permissions:
  #      id-token: write
  #      contents: read
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true
  #         lfs: false
  #     - name: Install OIDC Client from Core Package
  #       run: npm install @actions/core@1.6.0 @actions/http-client
  #     - name: Get Id Token
  #       uses: actions/github-script@v6
  #       id: idtoken
  #       with:
  #          script: |
  #              const coredemo = require('@actions/core')
  #              return await coredemo.getIDToken()
  #          result-encoding: string
  #     - name: Build And Deploy
  #       id: builddeploy
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_POND_0613F1A03 }}
  #         action: "upload"
  #         ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
  #         # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
  #         app_location: "/" # App source code path
  #         api_location: "" # Api source code path - optional
  #         output_location: "dist/apps/golfing" # Built app content directory - optional
  #         github_id_token: ${{ steps.idtoken.outputs.result }}
  #         ###### End of Repository/Build Configurations ######

#   close_pull_request_job:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed'
#     runs-on: ubuntu-latest
#     name: Close Pull Request Job
#     steps:
#       - name: Close Pull Request
#         id: closepullrequest
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           action: "close"
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy frontend and backend app to Azure

# on:
#     push:
#         branches:
#             - release
#     workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and zip apps from /dist
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --if-present
                  # npm run test --if-present

            - name: Zip artifacts for deployment
              run: |
                  echo ${GITHUB_WORKSPACE}
                  cd ${GITHUB_WORKSPACE}/dist/apps/rcmnd-api/ && zip ${GITHUB_WORKSPACE}/rcmnd-api-release.zip ./* -r
                  cd ${GITHUB_WORKSPACE}/dist/apps/data-api/ && zip ${GITHUB_WORKSPACE}/data-api-release.zip ./* -r
                  cd ${GITHUB_WORKSPACE}/dist/apps/golfing/ && zip ${GITHUB_WORKSPACE}/golfing-release.zip ./* -r

            - name: Upload golfing artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: golfing
                  path: golfing-release.zip

            - name: Upload data-api artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: data-api
                  path: data-api-release.zip

            - name: Upload rcmnd-api artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: rcmnd-api
                  path: rcmnd-api-release.zip

    deploy-golfing:
        runs-on: ubuntu-latest
        name: Deploy Angular Frontend
        needs: build
        environment:
            name: 'Production'

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: golfing

            - name: Unzip artifact for deployment
              run: unzip golfing-release.zip

            - name: Deploy to static azure web app
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_POND_0613F1A03 }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  app_location: '/' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'dist/apps/golfing' # Built app content directory - optional
                  github_id_token: ${{ steps.idtoken.outputs.result }}

    deploy-data-api:
        runs-on: ubuntu-latest
        name: Deploy NestJs data-api backend
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: data-api

            - name: Unzip artifact for deployment
              run: unzip data-api-release.zip

            - name: Install dependencies
              run: npm install

            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'golfing-data-api'
                  slot-name: 'Production'
                  publish-profile: ${{ secrets.AZURE_WEB_APPS_API_TOKEN_GOLFING_DATA_API }}
                  package: .

    deploy-rcmnd-api:
        runs-on: ubuntu-latest
        name: Deploy NestJs rcmnd-api backend
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: rcmnd-api

            - name: Unzip artifact for deployment
              run: unzip rcmnd-api-release.zip

            - name: Install dependencies
              run: npm install

            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'golfing-api-neo4j'
                  slot-name: 'Production'
                  publish-profile: ${{ secrets.AZURE_WEB_APPS_API_TOKEN_GOLFING_API_NEO4J }}
                  package: .